export const voitures = [
  {
    id: 1,
    nom: "Tesla Model 3",
    prix: 55000,
    quantite: 3,
    image: "/assets/a.jpg",
    video: "",
    description: "Voiture électrique performante avec 400 km d'autonomie.",
    categorie: "Électrique",
  },
  {
    id: 2,
    nom: "BMW X5",
    prix: 75000,
    quantite: 2,
    image: "/assets/mercedes-AMG-One.jpg",
    video: "",
    description: "SUV de luxe puissant et confortable.",
    categorie: "SUV",
  },
  {
    id: 3,
    nom: "Peugeot 208",
    prix: 23000,
    quantite: 5,
    image: "/assets/.jpg",
    video: "",
    description: "Citadine pratique et économique.",
    categorie: "Compacte",
  },
  {
    id: 4,
    nom: "Mercedes AMG One",
    prix: 250000,
    quantite: 1,
    image: "/assets/a.jpg",
    video: "",
    description: "Hypercar inspirée de la Formule 1, alliant performance et design.",
    categorie: "Sportive",
  },
];